### ISSUE TITLE
No ::json() method in Parser class (not library or generated)

### ISSUE THREAD

**Issue by stepanchvatik** [antlr/antlr-php-runtime#13]
Hello, I tried to go step by step through your tutorial and I created my grammar, ran command in terminal and put some code in php file. But to get $tree (ParseTreeWalker arg) I need to do $parser::json(), which is undefined... any ideas?

**Comment by mtouellette** [comment]
@stepanchvatik the json method is generated for the JSON grammer.  Your grammar will produce a different method.
