### ISSUE TITLE
PHP 8.X Support

### ISSUE THREAD

**Issue by nikcani** [antlr/antlr-php-runtime#25]
## ✨ Feature request
Please release a version with PHP 8.1 (and higher) support.

### Alternatives
Currently I am using the master branch because it is already implemented but not released.

**Comment by marcospassos** [comment]
I'm holding until the corresponding ANTLR version is out, which fortunately should happen over the next few days.

**Comment by marcospassos** [comment]
Version 0.7 is now out.
