### ISSUE TITLE
Antlr 4.10 = antlr-php-runtime version ????

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr-php-runtime#26]
## 🐞 Bug report
[This change to the Antlr PHP runtime was made 11 days ago for Antlr 4.10.](https://github.com/antlr/antlr-php-runtime/commit/5f2a2ddfd295ad83917dc3753ea5d4a4c252ca35). But we only have [this version from February of antlr-php-runtime in Composer](https://packagist.org/packages/antlr/antlr4-php-runtime#0.6.0). It's probably in the works, but just in case, this bug report can be used to track.

**Comment by marcospassos** [comment]
Version 0.7 is now out.
