### ISSUE TITLE
trying to execute the example

### ISSUE THREAD

**Issue by matthewmorrone** [antlr/antlr-php-runtime#29]
## 🐞 Bug report
I'm trying to set up antlr in PHP as per the readme, and come across these issues:

`PHP Fatal error:  Uncaught Error: Interface "Antlr\Antlr4\Runtime\Tree\ParseTreeListener" not found in C:\xampp\htdocs\diachron-db\parser\json.php:14
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\diachron-db\parser\json.php on line 14`

In VSCode, I'm getting these errors from intelephense:

`Undefined type 'JsonParser\JSONLexer'.intelephense(1009)`
`Undefined type 'JsonParser\JSONParser'.intelephense(1009)`

### Steps to reproduce
1. antlr4 -Dlanguage=PHP JSON.g4
2. php json.php example.json

### Screenshots
![image](https://user-images.githubusercontent.com/491280/181659198-58078f2b-7fa8-4f5b-a13d-0e85b646229d.png)

### Additional Context
According to the example in the readme, `antlr4 -Dlanguage=PHP JSON.g4` generates all of its files in a folder called "parser", but in fact it generates all of them in the working directory. `antlr4 -Dlanguage=PHP JSON.g4 -o parser` does this.

**Comment by marcospassos** [comment]
@matthewmorrone, did you set up the autoloader?
