### ISSUE TITLE
JSON.g4 parser generation leads to symbol conflict (array)

### ISSUE THREAD

**Issue by prasad83** [antlr/antlr-php-runtime#3]
```antlr4 -Dlanguage=PHP JSON.g4```

```error(134): JSON.g4:20:0: symbol array conflicts with generated code in target language or runtime```

Replacing (array) to (arr) in JSON.g4 works.

**Comment by marcospassos** [comment]
Hi @prasad83!

Yeah, that's because `array` is a reserved word in PHP. What about opening an issue (and a PR) on https://github.com/antlr/grammars-v4 with this change?

**Comment by prasad83** [comment]
thank you @marcospassos - I did send a [PR](https://github.com/antlr/grammars-v4/pull/1653)

**Comment by marcospassos** [comment]
Closing as it seems to be addressed by https://github.com/antlr/grammars-v4/pull/1653
