### ISSUE TITLE
There is no release of Antlr PHP for 4.11.1

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr-php-runtime#30]
## 🐞 Bug report
If you try to use Antlr 4.11.1 tool to generate a parser for the PHP target then run it using https://packagist.org/packages/antlr/antlr4-php-runtime version 0.7.0--the latest--you get "ANTLR Tool version 4.11.1 used for code generation does not match the current runtime version 4.10". Waiting a couple of months for an update in order to test grammars-v4. Ty.

**Comment by marcospassos** [comment]
Hi @kaby76, I'll bump it over the next few days. Thank you for reporting!

**Comment by marcospassos** [comment]
Feel free to open a PR if you're in a hurry.

**Comment by marcospassos** [comment]
[Done](https://github.com/antlr/antlr-php-runtime/releases/tag/0.7.1)!

**Comment by kaby76** [comment]
Thanks!
