### ISSUE TITLE
Implement automated tests

### ISSUE THREAD

**Issue by denis-rossati** [antlr/antlr-php-runtime#37]
## ✨ Request

I saw that there are lots of code and no automated tests. We should consider at least unitary tests to improve the code maintainability and maybe integration tests as well!

I have some free time to work this out on a daily basis after work. Let me know what you think and we can discuss what and how we can do :)

**Comment by marcospassos** [comment]
The ANTLR test suite functionally tests this runtime. But we do need unit tests for the runtime, indeed. Feel free to contribute!
