### ISSUE TITLE
Exclude QA / CI files from release using .gitattributes

### ISSUE THREAD

**Issue by dkarlovi** [antlr/antlr-php-runtime#41]
## ✨ Feature request

Exclude all but the necessary files from the released package using `.gitattributes`

### Motivation

It removes all but production files from the released package.

### Example

https://github.com/symfony/config/blob/7.0/.gitattributes

### Alternatives

The unnecessary files stay in the package.

### Additional context

It's good practice to remove all but the strictly necessary files for production use from releases, this can typically substantially reduce the disk size (which is important for containerized apps), but it's all good hygiene practice.

**Comment by marcospassos** [comment]
Hi @dkarlovi, feel free to open a PR.

**Comment by dkarlovi** [comment]
@marcospassos I don't understand, you're closing the issue and marking it as completed, but telling me to open a PR? Is it completed or not? If not, why close the issue? Sending mixed signals here. 😀

**Comment by marcospassos** [comment]
I'm happy to accept a PR, but there's no need for an issue for that. Just submit the PR and we can take it from there.

**Comment by dkarlovi** [comment]
I don't really understand this workflow since issues are a to-do list, but OK. 👍
