### ISSUE TITLE
Can you tag a 0.4 release to get ANTLR version 4.8 in the RuntimeMetaData.php?

### ISSUE THREAD

**Issue by HermanPeeren** [antlr/antlr-php-runtime#6]
When Composer installs the latest version of the PHP Runtime (following the installation instructions), it installs version 0.3. But in RuntimeMetaData.php that version says it is for ANTLR 4.7.2. In the repo (master) that ANTLR- version is now updated to 4.8. 

After Composer install latest version you get an error and have to manually update 4.7.2 to 4.8. Releasing a new version of the PHP Runtime solves this.

**Comment by marcospassos** [comment]
Hi @HermanPeeren! Thank you for pointing it out. 

I just released a new version. Please let me know if the issue has been fixed.

**Comment by HermanPeeren** [comment]
Yes, works. Thank you!
