### ISSUE TITLE
Is it really needed ANTLR?

### ISSUE THREAD

**Issue by acuna-public** [antlr/antlr-php-runtime#9]
Seems I've missed something, but is it really need an ANTLR installed for it if it's an PHP runtime which can be loaded independently with PHP? Thanks.

**Comment by marcospassos** [comment]
The [ANTLR is needed for generating the parser](https://github.com/antlr/antlr-php-runtime#3-generate-your-parser), which depends on the runtime.

**Comment by acuna-public** [comment]
Ah, *depends* on the runtime, get it, thanks, I though it's plain PHP implementation like another generators like yacc or lemon :(

**Comment by marcospassos** [comment]
@acuna-public, it's a plain PHP implementation. The ANTLR is a parser generator, meaning that you write a grammar, and ANTLR generates the PHP parser for you. From this point, you don't depend on ANTLR anymore (or at least until you need to update the grammar and regenerate the parser). The generated parser depends on the runtime library.

**Comment by acuna-public** [comment]
Aah, I see, seems that I don't get it right what is runtime means, thank you.

And I don't want to create another issue, so can I ask you there, I see the PhpLexer.g4 in grammar folder, so does it means that ANTLR can generate lexers too, because I know that it's only parsers generator tool?
